### ISSUE TITLE
`KeyError: 'use_scale_latent_for_hires_fix'` error resulting in `SyntaxError: Unexpected token I in JSON at position 0`

### ISSUE THREAD

**Issue by pixel3rr0r** [TiagoMarinho/Soph#14]
I have installed the bot as well as the web UI according to the instructions, launched the web UI with args `--api` and the bot with `--experimental-json-modules`. Everything else has been left untouched.

Sending prompts leads to receiving `SyntaxError: Unexpected token I in JSON at position 0` exceptions. Looking at the web UI console, the following error gets thrown multiple times:
```
...
firstphase_width/firstphase_height no longer supported; use hr_scale
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  ...
  File "E:\...\Projects\stable-diffusion-webui\modules\processing.py", line 462, in process_images
    stored_opts = {k: opts.data[k] for k in p.override_settings.keys()}
  File "E:\...\Projects\stable-diffusion-webui\modules\processing.py", line 462, in <dictcomp>
    stored_opts = {k: opts.data[k] for k in p.override_settings.keys()}
KeyError: 'use_scale_latent_for_hires_fix'
```

I assume this occurs due to a change in the text2img API. So I tried changing the payload format to match the one in the docs, to no avail. Any ideas what's going wrong?

Another issue is that the error cannot be sent on Discord, as the bot already has responded to the last interaction, but this should be its own ticket.

**Comment by pixel3rr0r** [comment]
Fixed by removing line 66 from `src\artificial intelligence\requestimage.js` (`"use_scale_latent_for_hires_fix": latentSpace,`). May this should be looked into?

**Comment by TiagoMarinho** [comment]
Will commit a fix for this soon, recent webUI commit changed how highres-fix works through the API, so that's what caused it.
