### ISSUE TITLE
DiscordAPIError[50035]: Invalid Form Body

### ISSUE THREAD

**Issue by LulzRose** [TiagoMarinho/Soph#39]
Upon deploying the bot I am receiving the following error, any idea why it could be displaying?

`npm run deploy

> soph@1.0.0 deploy
> node src/deploy-commands.js

(node:4220) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Started refreshing 8 application (/) commands.
DiscordAPIError[50035]: Invalid Form Body
0.options[2].choices[BASE_TYPE_MAX_LENGTH]: Must be 25 or fewer in length.
1.options[3].choices[BASE_TYPE_MAX_LENGTH]: Must be 25 or fewer in length.
    at handleErrors (C:\Users\Rose\Downloads\!Applications\Soph\node_modules\@discordjs\rest\dist\index.js:640:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (C:\Users\Rose\Downloads\!Applications\Soph\node_modules\@discordjs\rest\dist\index.js:1021:23)
    at async SequentialHandler.queueRequest (C:\Users\Rose\Downloads\!Applications\Soph\node_modules\@discordjs\rest\dist\index.js:862:14)
    at async REST.request (C:\Users\Rose\Downloads\!Applications\Soph\node_modules\@discordjs\rest\dist\index.js:1387:22)
    at async file:///C:/Users/Rose/Downloads/!Applications/Soph/src/deploy-commands.js:25:22 {
  requestBody: {
    files: undefined,
    json: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  rawError: {
    message: 'Invalid Form Body',
    code: 50035,
    errors: { '0': [Object], '1': [Object] }
  },
  code: 50035,
  status: 400,
  method: 'PUT',
  url: 'https://discord.com/api/v10/applications/1241907566242430997/commands'
}`

**Comment by TiagoMarinho** [comment]
Discord only allows for up to 25 options in a single command parameter. As such, the `model` field can only possibly accept 25 models. If you have more, this issue will happen. I'll add something to clamp the number of models available on the command automatically, but it will result on random models not being shown.

**Comment by TiagoMarinho** [comment]
Please be so kind as to test the fix and tell me how it went

**Comment by TiagoMarinho** [comment]
Talked to the user directly, problem is fixed now
